// <auto-generated />
using System;
using DNDProject.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DNDProject.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250929075640_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DNDProject.Api.Models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LastFillPct")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastPickupDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Material")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreferredPickupFrequencyDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeLiters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("WeeklyAmountKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Containers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastFillPct = 82.0,
                            Material = 1,
                            PreferredPickupFrequencyDays = 14,
                            SizeLiters = 2500,
                            Type = "Plast",
                            WeeklyAmountKg = 120.0
                        },
                        new
                        {
                            Id = 2,
                            LastFillPct = 46.0,
                            Material = 2,
                            PreferredPickupFrequencyDays = 21,
                            SizeLiters = 7000,
                            Type = "Jern",
                            WeeklyAmountKg = 900.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
