// <auto-generated />
using System;
using DNDProject.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DNDProject.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250929085935_AddHistory")]
    partial class AddHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DNDProject.Api.Models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LastFillPct")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastPickupDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Material")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreferredPickupFrequencyDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeLiters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("WeeklyAmountKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Containers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastFillPct = 82.0,
                            Material = 1,
                            PreferredPickupFrequencyDays = 14,
                            SizeLiters = 2500,
                            Type = "Plast",
                            WeeklyAmountKg = 120.0
                        },
                        new
                        {
                            Id = 2,
                            LastFillPct = 46.0,
                            Material = 2,
                            PreferredPickupFrequencyDays = 21,
                            SizeLiters = 7000,
                            Type = "Jern",
                            WeeklyAmountKg = 900.0
                        });
                });

            modelBuilder.Entity("DNDProject.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DNDProject.Api.Models.PickupEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Co2Kg")
                        .HasColumnType("REAL");

                    b.Property<int>("ContainerId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("REAL");

                    b.Property<double?>("FillPct")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId", "Timestamp");

                    b.ToTable("PickupEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContainerId = 1,
                            FillPct = 88.0,
                            Timestamp = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 110.0
                        },
                        new
                        {
                            Id = 2,
                            ContainerId = 1,
                            FillPct = 92.0,
                            Timestamp = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 125.0
                        },
                        new
                        {
                            Id = 3,
                            ContainerId = 2,
                            FillPct = 51.0,
                            Timestamp = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 480.0
                        });
                });

            modelBuilder.Entity("DNDProject.Api.Models.Container", b =>
                {
                    b.HasOne("DNDProject.Api.Models.Customer", null)
                        .WithMany("Containers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DNDProject.Api.Models.PickupEvent", b =>
                {
                    b.HasOne("DNDProject.Api.Models.Container", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("DNDProject.Api.Models.Customer", b =>
                {
                    b.Navigation("Containers");
                });
#pragma warning restore 612, 618
        }
    }
}
